root/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from root import db, ma, login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    email = db.Column(db.String(128), unique=True)
    pw_hash = db.Column(db.String(128))

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.pw_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.pw_hash, password)

class Task(db.Model):
    __tablename__ = 'tasks'
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(140), nullable=False)
    completed = db.Column(db.Boolean, default=False)

    def __init__(self, description, completed=False):
        self.description = description
        self.completed = completed

class TaskSchema(ma.ModelSchema):
    class Meta:
        model = Task

root/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

class RegisterForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), 
        EqualTo('confirm_pass', message='Passwords is different')])
    confirm_pass = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

class UpdateForm(FlaskForm):
    name = StringField('Name')
    email = StringField('Email')
    # password = PasswordField('Password', validators=[DataRequired(), 
    #     EqualTo('confirm_pass', message='Passwords is different')])
    # confirm_pass = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

root/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_marshmallow import Marshmallow
from flask_login import LoginManager
from flask_restful import Api

app = Flask(__name__)

app.config.from_pyfile('config.py')
# app.config['SECRET_KEY'] = 'mysecret'

# basedir = os.path.abspath(os.path.dirname(__file__))
# app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
# app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)
ma = Marshmallow(app)
api = Api(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

root/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, login_user,logout_user, current_user

from root import db
from root.models import User
from root.users.forms import LoginForm, RegisterForm, UpdateForm

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register_user():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            form.name.data,
            form.email.data,
            form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks your registratioin!')
        return redirect(url_for('index'))
    return render_template('register_user.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        user.check_password(form.password.data)
        login_user(user) 
        flash('Logged In Successfully.')
        return redirect(url_for('index'))
    return render_template('login.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    flash('Logged Out Successfully.')
    return redirect(url_for('index'))
    
@users.route('/account', methods=['GET', 'POST'])
@login_required
def update_profile():
    form = UpdateForm()
    if form.validate_on_submit():
        flash(form.name.data)
        current_user.name = form.name.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Updated User Profile')
        return redirect(url_for('index'))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.email.data = current_user.email
    return render_template('account.html', form=form)

root/templates/account.html
{% extends 'base.html' %}

{% block content %} 
<form action="" method="POST"> 
    {{ form.hidden_tag() }}
    {{ form.name.label() }} {{ form.name() }} <br>
    {{ form.email.label() }} {{ form.email() }} <br>
    {{ form.submit() }}
</form>
{% endblock content %}

root/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-11/css/all.min.css">
<!-- <link rel="stylesheet" href="style.css"> -->
<title>Title</title>
<style>
    .flash-alert {
        width: 100vw;
        display: none;
        position: absolute;
    }
</style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('index') }}">Navbar</a>
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <div class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <a class="nav-item nav-link active" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.update_profile') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">LogOut</a> 
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">LogIn</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register_user') }}">Register</a> 
                    {% endif %}
                </dif>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    {% for msg in get_flashed_messages() %}
        <div class="flash-alert alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ msg }}
        </div>
        
    {% endfor %}

    {% block content %}
    
    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script>
          $(".flash-alert").fadeIn(400).delay(1000).fadeOut(400);
        </script>
</body>
</html>

root/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome My Site</h1>
    </div>

{% endblock content %}

root/templates/login.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST"> 
    {{ form.hidden_tag() }}
    {{ form.email.label() }} {{ form.email() }} <br>
    {{ form.password.label() }} {{ form.password() }} <br>
    {{ form.submit() }}
</form>

{% endblock content %}

root/templates/register_user.html
{% extends 'base.html' %}

{% block content %} 
<form action="" method="POST"> 
    {{ form.hidden_tag() }}
    {{ form.name.label() }} {{ form.name() }} <br>
    {{ form.email.label() }} {{ form.email() }} <br>
    {{ form.password.label() }} {{ form.password() }} <br>
    {{ form.confirm_pass.label() }} {{ form.confirm_pass() }} <br>
    {{ form.submit() }}
</form>
{% endblock content %}